Repository pimutils/khal, pull requests merged in 2022-06, with the labels that each got.

#1030 Use new syntax for validate. Fixes #993.
  doc/source/conf.py
  khal/settings/settings.py
  khal/settings/utils.py
  tests/settings_test.py
Labels: upstream

#859 Fix event creation for future events
  CHANGELOG.rst
  khal/khalendar/event.py
  tests/event_test.py
  tests/ics/cal_dt_two_tz.ics
  tests/ics/event_dt_simple_inkl_vtimezone.ics
Labels: type: bug

#1139 Fix error logging in ikhal
  CHANGELOG.rst
  khal/ui/__init__.py
Labels: type: bug

#1144 Drop support for python 3.6 and 3.7
  .github/workflows/ci.yml
  .readthedocs.yml
  CHANGELOG.rst
  README.rst
  doc/source/index.rst
  doc/source/install.rst
  setup.py
  tox.ini
Labels: breaks compatibility

#1044 WIP: Typing party
  CHANGELOG.rst
  khal/__init__.py
  khal/calendar_display.py
  khal/cli.py
  khal/configwizard.py
  khal/controllers.py
  khal/custom_types.py
  khal/khalendar/__init__.py
  khal/khalendar/backend.py
  khal/khalendar/event.py
  khal/khalendar/khalendar.py
  khal/khalendar/vdir.py
  khal/parse_datetime.py
  khal/settings/__init__.py
  khal/settings/settings.py
  khal/terminal.py
  tests/backend_test.py
  tests/parse_datetime_test.py
  tox.ini
Labels: upstream
